/*
 * This source file was generated by the Gradle 'init' task
 */
package com.bank;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App app = new App();
        assertNotNull(app.getGreeting(), "app should have a greeting");
        assertTrue(app.getGreeting().contains("Hello Thang Handsome! max(2 + 3, 10) = 10"), "app should use util sum function");
    }
}
