/*
 * This source file was generated by the Gradle 'init' task
 */
package com.bank;

import com.bank.util.Utils;
import com.google.common.collect.ImmutableSet;

public class App {
    public String getGreeting() {
        int sum = Utils.sum(2, 3);
        int resultWithFallback = Math.max(sum, 10);
        return "Hello Thang Handsome! max(2 + 3, 10) = " + resultWithFallback;
    }

    public static void main(String[] args) {
      ImmutableSet<String> names = COLOR_NAMES;

      for (String name : names) {
        System.out.println(name);
      }

      // app only sees util's String API; Commons Lang stays internal to util.
      System.out.println("color range: " + Utils.colorRange());

      System.out.println(new App().getGreeting());
    }

    private static final ImmutableSet<String> COLOR_NAMES = ImmutableSet.of(
        "red",
        "orange",
        "yellow",
        "green",
        "blue",
        "purple");
}
