/*
 * This source file was generated by the Gradle 'init' task
 */
package com.bank;

import com.bank.util.Utils;

public class App {
    public String getGreeting() {
        int sum = Utils.sum(2, 3);
        int resultWithFallback = Math.max(sum, 10);
        return "Hello Thang Handsome! max(2 + 3, 10) = " + resultWithFallback;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
