/*
 * This source file was generated by the Gradle 'init' task
 */
package com.bank;

import com.bank.util.Utils;

public class App {
    public String getGreeting() {
        return "Hello Thang Handsome! 2 + 3 = " + Utils.sum(2, 3);
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
